module.exports =
{
    "email": "Courriel",
    "pwd": "Mot de passe",
    "pwdConfirm": "Confirmer mot de passe",
    "pwdForgot": "Mot de passe oublié?",
    "connection": "Connexion",
    "inscription": "S'inscrire",
    "facebookSignin": "images/facebook.png",
    "googleSignin": "images/google+.png",
    "firstName": "Prénom",
    "familyName": "Nom de famille",
    "birthDate": "Date de naissance",
    "loginLabel": "Connexion",
    "signupLabel": "Inscription",
    "emptyInput": "Ce champs ne peut pas être vide!",
    "differentPwd": "Les mots de passe sont différents!",
    "errorDateEmpty": "La date de naissance doit être sélectionné!",
    "day": "Jour",
    "month": "Mois",
    "year": "Année",
    "january": "janvier",
    "february": "février",
    "march": "mars",
    "april": "avril",
    "may": "mai",
    "june": "juin",
    "july": "juillet",
    "august": "août",
    "september": "septembre",
    "october": "octobre",
    "november": "novembre",
    "december": "décembre"
};