module.exports =
{
    "email": "Courriel",
    "pwd": "Mot de passe",
    "pwdConfirm": "Confirmer mot de passe",
    "pwdForgot": "Mot de passe oubli\u00E9?",
    "connection": "Connexion",
    "inscription": "S'inscrire",
    "facebookSignin": "images/facebook.png",
    "googleSignin": "images/google+.png",
    "firstName": "Pr\u00E9nom",
    "familyName": "Nom de famille",
    "birthDate": "Date de naissance",
    "loginLabel": "Connexion",
    "signupLabel": "Inscription",
    "emptyInput": "Valeur incorrect",
    "incorrectName": "La valeur entr\u00E9e est incorrect",
    "differentPwd": "Les mots de passe sont diff\u00E9rents!",
    "errorDateEmpty": "La date de naissance doit \u00EAtre s\u00E9lectionn\u00E9e!",
    "day": "Jour",
    "month": "Mois",
    "year": "Ann\u00E9e",
    "january": "janvier",
    "february": "février",
    "march": "mars",
    "april": "avril",
    "may": "mai",
    "june": "juin",
    "july": "juillet",
    "august": "ao\u00FBt",
    "september": "septembre",
    "october": "octobre",
    "november": "novembre",
    "december": "d\u00E9cembre"
};